version: '3'

services:
  mysqldb:
    image: mysql:5.7
    container_name: my-sql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - mysql_cluster_net

  app: 
    build: .
    restart: on-failure
    env_file: ./.env
    ports: 
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - DB_URL=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - UPLOAD_PATH=$SPRING_UPLOAD_PATH
    volumes: 
      - ./uploads:$SPRING_UPLOAD_PATH
    links:
      - redis
    depends_on:
      - mysqldb
    networks:
      - mysql_cluster_net

  redis:
    image: redis
    ports:
     - "6379:6379"
    networks:
      - mysql_cluster_net 


networks:
  mysql_cluster_net:
    driver: bridge